import * as fs from 'fs';
import * as path from 'path';

// Load facts
import { HANDBOOK_FACTS } from '../src/handbookFacts';

const dataContent = fs.readFileSync(path.resolve(process.cwd(), 'src/data.ts'), 'utf-8');

// The mapping of existing questions to fact IDs
const qIdToFacts: { [qId: string]: string[] } = {
  q1: ['fact-traffic-light-flashing-yellow'],
  q2: ['fact-provisional-passengers'],
  q3: ['fact-provisional-curfew'],
  q4: ['fact-school-zone-speed-children'],
  q5: ['fact-center-left-turn-distance'],
  q6: ['fact-uturn-residential-clearance'],
  q7: ['fact-uturn-business-districts-rule'],
  q8: ['fact-hill-parking-downhill'],
  q9: ['fact-scan-road-10seconds'],
  q10: ['fact-right-turn-red-arrow'],
  q11: ['fact-turnout-slow-vehicles'],
  q12: ['fact-hov-motorcycle-lane'],
  q13: ['fact-drive-bike-lane-limit'],
  q14: ['fact-traffic-light-red-arrow'],
  q15: ['fact-pass-on-right-allowed'],
  q16: ['fact-exit-highway-signal'],
  q17: ['fact-right-turn-bus-lane'],
  q18: ['fact-pass-on-right-allowed'],
  q19: ['fact-uturn-visibility-distance'],
  q20: ['fact-uturn-divided-highway-barrier'],
  q21: ['fact-traffic-light-red'],
  q22: ['fact-traffic-light-solid-green'],
  q23: ['fact-truck-no-zone-blind'],
  q24: ['fact-emergency-vehicle-follow-distance'],
  q25: ['fact-sign-stop'],
  q26: ['fact-streetcar-safety-zone-speed'],
  q27: ['fact-dim-beams-oncoming-500ft'],
  q28: ['fact-flag-bumper-cargo-4feet'],
  q29: ['fact-traffic-light-flashing-red'],
  q30: ['fact-truck-stopping-distance-feet'],
  q31: ['fact-provisional-exception-medical'],
  q32: ['fact-provisional-exception-school'],
  q33: ['fact-signal-turn-100ft'],
  q34: ['fact-hand-signal-left-arm'],
  q35: ['fact-hand-signal-right-arm'],
  q36: ['fact-hand-signal-slow-stop-arm'],
  q37: ['fact-signal-freeway-5seconds'],
  q38: ['fact-headlights-after-sunset'],
  q39: ['fact-headlights-before-sunrise'],
  q40: ['fact-dim-beams-following-300ft'],
  q41: ['fact-uturn-residential-clearance'],
  q42: ['fact-uturn-residential-clearance'],
  q43: ['fact-uturn-divided-highway-barrier'],
  q44: ['fact-uturn-divided-highway-barrier'],
  q45: ['fact-uturn-divided-highway-barrier'],
  q46: ['fact-uturn-visibility-distance'],
  q47: ['fact-uturn-visibility-distance'],
  q48: ['fact-uturn-visibility-distance'],
  q49: ['fact-uturn-visibility-distance'],
  q50: ['fact-uturn-business-districts-rule'],
  q51: ['fact-traffic-light-broken'],
  q52: ['fact-traffic-light-broken'],
  q53: ['fact-ped-dont-walk-flashing'],
  q54: ['fact-hill-parking-uphill'],
  q55: ['fact-hill-parking-uphill'],
  q56: ['fact-hill-parking-uphill'],
  q57: ['fact-hill-parking-downhill'],
  q58: ['fact-traffic-light-solid-green'],
  q59: ['fact-hill-parking-downhill'],
  q60: ['fact-traffic-light-broken'],
  q61: ['fact-truck-no-zone-blind'],
  q62: ['fact-mountain-rightofway'],
  q63: ['fact-collision-report-sr1-dmv'],
  q64: ['fact-dui-test-refusal'],
  q65: ['fact-skid-release-accelerator-no-brakes'],
  q66: ['fact-truck-no-zone-blind'],
  q67: ['fact-pedestrian-white-canes'],
  q68: ['fact-pedestrian-white-canes'],
  q69: ['fact-hill-parking-uphill'],
  q70: ['fact-tailgate-three-second-rule'],
  q71: ['fact-provisional-curfew'],
  q72: ['fact-provisional-passengers'],
  q73: ['fact-class-c-license'],
  q74: ['fact-class-c-license'],
  q75: ['fact-instruction-permit-btw'],
  q76: ['fact-knowledge-btw-tests'],
  q77: ['fact-knowledge-btw-tests'],
  q78: ['fact-instruction-permit-btw'],
  q79: ['fact-knowledge-btw-tests'],
  q80: ['fact-colored-curb-green'],
  q81: ['fact-drive-bike-lane-limit'],
  q82: ['fact-school-zone-speed-children'],
  q83: ['fact-hill-parking-downhill'],
  q84: ['fact-hill-parking-downhill'],
  q85: ['fact-slow-moving-vehicle-speed'],
  q86: ['fact-parking-curb-distance'],
  q87: ['fact-bike-passing-clearance'],
  q88: ['fact-move-over-law-tows'],
  q89: ['fact-colored-curb-white'],
  q90: ['fact-turnout-slow-vehicles'],
  q91: ['fact-truck-no-zone-blind'],
  q92: ['fact-mountain-rightofway'],
  q93: ['fact-dui-test-refusal'],
  q94: ['fact-dui-open-container-vehicle'],
  q95: ['fact-dui-test-refusal'],
  q96: ['fact-mountain-rightofway'],
  q97: ['fact-mountain-rightofway'],
  q98: ['fact-bac-limit-under-21'],
  q99: ['fact-pedestrian-white-canes'],
  q100: ['fact-dui-open-container-vehicle'],
  q101: ['fact-single-yellow-line'],
  q102: ['fact-single-yellow-line'],
  q103: ['fact-yellow-barrier-lines'],
  q104: ['fact-center-left-turn-distance'],
  q105: ['fact-turnout-slow-vehicles'],
  q106: ['fact-broken-yellow-line'],
  q107: ['fact-hov-motorcycle-lane'],
  q108: ['fact-hov-motorcycle-lane'],
  q109: ['fact-double-solid-white-lines'],
  q110: ['fact-broken-yellow-line'],
  q111: ['fact-headlights-dark-1000ft'],
  q112: ['fact-headlights-wipers-running'],
  q113: ['fact-headlights-after-sunset'],
  q114: ['fact-headlights-before-sunrise'],
  q115: ['fact-class-c-license'],
  q116: ['fact-class-c-license'],
  q117: ['fact-skid-release-accelerator-no-brakes'],
  q118: ['fact-windshield-lower-corner-passenger'],
  q119: ['fact-windshield-lower-corner-driver'],
  q120: ['fact-class-c-license'],
  q121: ['fact-distracted-cell-minors-rules'],
  q122: ['fact-distracted-cell-minors-rules'],
  q123: ['fact-hearing-headset-dual-earplug'],
  q124: ['fact-animal-abandonment-highway'],
  q125: ['fact-scan-road-10seconds'],
  q126: ['fact-signal-curb-side'],
  q127: ['fact-skid-release-accelerator-no-brakes'],
  q128: ['fact-pickup-cargo-bed-seats'],
  q129: ['fact-uturn-visibility-distance'],
  q130: ['fact-skid-release-accelerator-no-brakes'],
  q131: ['fact-pass-on-right-allowed'],
  q132: ['fact-parking-curb-distance'],
  q134: ['fact-sign-yield'],
  q135: ['fact-sign-yield'],
  q136: ['fact-exit-highway-signal'],
  q137: ['fact-hill-parking-uphill'],
  q138: ['fact-emergency-flashers-hazard'],
  q139: ['fact-uturn-residential-clearance'],
  q140: ['fact-uturn-residential-clearance'],
  q141: ['fact-uturn-residential-clearance'],
  q142: ['fact-signal-turn-100ft'],
  q143: ['fact-signal-empty-road'],
  q144: ['fact-signal-freeway-5seconds'],
  q145: ['fact-mountain-rightofway'],
  q146: ['fact-class-c-license']
};

console.log("Analyzing high-priority facts coverage...");

const highPriorityFacts = HANDBOOK_FACTS.filter(f => f.priority === 'high');
const mappedFactIds = new Set(Object.values(qIdToFacts).flat());

const uncoveredHighPriority = highPriorityFacts.filter(f => !mappedFactIds.has(f.id));

console.log(`\nFound ${highPriorityFacts.length} high-priority facts.`);
console.log(`Found ${uncoveredHighPriority.length} uncovered high-priority facts:`);
uncoveredHighPriority.forEach(f => {
  console.log(`- ${f.id}: "${f.fact}" (Page ${f.page})`);
});
